name: Daily Warframe DB Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-database:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # NON SERVE PIÃ™ "npm install warframe-items"
      # Lo script scarica tutto da solo usando https nativo.

      - name: Esegui script di aggiornamento
        run: node scripts/update-db.js

      - name: Commit e Push delle modifiche
        run: |
          git config --global user.name 'Ordis Bot'
          git config --global user.email 'ordis-bot@users.noreply.github.com'
          git add public/database_api/*.json
          if git diff --staged --quiet; then
            echo "Nessun cambiamento."
          else
            git commit -m "Auto-update: Warframe Database Daily Sync"
            git push
          fi